### ISSUE TITLE
about ground truth pose and bev cloud?

### ISSUE THREAD

**Issue by grdiv** [adin-pro/avp_mapping#1]
Hello, It's a greate work! I met a question: I have ground truth pose on camera coordinate, and i use your/avp-slam-plus's  [img2BevCloud](https://github.com/adin-pro/avp_mapping/blob/94c7044e592de7760440b51eef58f03bee46d358/src/models/camera/camera_model.cpp#L35), but then how can I use the ground truth pose to stitch these bev cloud? in other words, how can i transform pose to bev cloud's coordinate? although bev cloud is in ground plane, but i found they didn't on it, they have a height difference. thank you.

**Comment by adin-pro** [comment]
sorry for late response. I am not sure if you still have this question. 

> how can i transform pose to bev cloud's coordinate

you need the transformation between camera coordinate and bev coordinate. 

In the real world, this transformation is obtained by calibrating the camera extrinsic parameters. But in this simulation project, the extrinsic parameter of the camera can be obtained by TFListener.

in `data_pretrate_flow.cpp` line 49. Here we get $T_{bev}^{cam0}$. The bev coordinate system is equivalent to base_link here.

` base_to_camera0_ptr_ =
      std::make_shared<TFListener>(nh, "/camera0_link", "/base_link");`

then you can transform your GroundTruth from camera coordinate to bev coordinate:

$GT_{bev} = (T_{base}^{cam0})^{-1} * GT_{cam0} * T_{base}^{cam0}$

**Comment by grdiv** [comment]
Problem solved, but thank you very much for your answer！！
